#!/bin/bash
# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

source $(dirname "$0")/libs/working_dir
source libs/catch_error

arch=$(uname -i)
if [ "${arch}" = "x86_64" ]; then
	# x86_64 is the default image
	tag="latest"
else
	tag="latest-${arch}"
fi

uname_r=$(uname -r)
uname_noarch=${uname_r%.*}
yum install anolis-repos -y
yum install sysstat -y
yum install podman yum-utils kernel-debuginfo-${uname_r} kernel-devel-${uname_r} --enablerepo=Plus-debuginfo --enablerepo=Plus -y
pip3 install sh pyyaml coloredlogs

container=$(podman ps -a | awk '$NF=="foosched"{print $1}')
if [ -n "$container" ]; then
	podman rm -f ${container}
fi
mkdir -p /tmp/work
podman run -itd --name=foosched -w /root/ -v /tmp/work:/root -v /usr/src/kernels:/usr/src/kernels -v /usr/lib/debug/lib/modules:/usr/lib/debug/lib/modules foosched/foosched-sdk:${tag} /bin/bash
podman exec -it foosched rm -rf /usr/local/lib/foosched
podman cp .. foosched:/usr/local/lib/foosched
cd /tmp/work
yumdownloader --source kernel-${uname_r} --enablerepo=Plus
podman exec -it foosched foosched-cli extract_src kernel-${uname_noarch}.src.rpm ./kernel
podman exec -it foosched foosched-cli init ${uname_r} ./kernel ./scheduler
